
import { GoogleGenAI, Modality } from "@google/genai";
import type { ImageFile } from '../types';

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export async function generateTryOnImage(
  personImage: ImageFile,
  clothingImage: { data: string; mimeType: string }
): Promise<string> {
  try {
    const model = 'gemini-2.5-flash-image';
    const prompt = `You are a virtual stylist. Take the first image of the person and the second image of the clothing item. Generate a new, photorealistic image of the person from the first image wearing the article of clothing from the second image. It is critical that the generated image perfectly matches the crop, scale, pose, expression, and background of the original photo of the person. Only the clothing should be changed.`;

    const personImagePart = {
      inlineData: {
        mimeType: personImage.mimeType,
        data: personImage.data,
      },
    };

    const clothingImagePart = {
      inlineData: {
        mimeType: clothingImage.mimeType,
        data: clothingImage.data,
      },
    };

    const textPart = {
      text: prompt,
    };
    
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [personImagePart, clothingImagePart, textPart],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return part.inlineData.data;
        }
    }
      
    throw new Error("No image was generated by the model.");

  } catch (error) {
    console.error("Error generating image with Gemini:", error);
    if (error instanceof Error && error.message.includes('API key not valid')) {
       throw new Error("The provided API key is not valid. Please check your configuration.");
    }
    throw new Error("Failed to generate the try-on image.");
  }
}